name: manhua_reader_flutter
description: A modern manga reader application built with Flutter
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  photo_view: ^0.15.0
  flutter_staggered_grid_view: ^0.7.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^12.1.3
  
  # File System
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  archive: ^4.0.7
  path: ^1.8.3
  image: ^4.1.0
  
  # Data
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  # Database - Drift for better isolate support
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  crypto: ^3.0.3
  pdfx: ^2.9.2
  tuple: ^2.0.0
  local_auth: ^2.1.6

  # Networking for multi-device sharing
  multicast_dns: ^0.3.2+4
  dio: ^5.4.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  network_info_plus: ^4.1.0
  device_info_plus: ^11.5.0

  # Network protocol clients
  webdav_client: ^1.2.2 # WebDAV client
  smb_connect: ^0.0.9
  dartssh2: ^2.13.0
  # 其他协议客户端暂时使用自实现方式避免依赖冲突

  # 设置页面相关
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

  # Code Generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1

  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true