server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: manhua-reader
  
  datasource:
    url: jdbc:h2:file:${app.data-path}/database/manhua;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  web:
    resources:
      static-locations: classpath:/static/,file:${app.data-path}/cache/,file:${app.data-path}/thumbnails/,file:${app.data-path}/covers/
      cache:
        period: 3600
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# 应用程序自定义配置
app:
  # 数据存储路径
  data-path: ${user.home}/.manhua-reader
  
  # 缓存配置
  cache:
    # 缓存大小限制（MB）
    max-size: 1024
    # 缓存过期时间（小时）
    expire-hours: 24
    # 缩略图缓存过期时间（小时）
    thumbnail-expire-hours: 168
    # 封面缓存过期时间（小时）
    cover-expire-hours: 168
  
  # 扫描配置
  scan:
    # 支持的漫画文件格式
    supported-formats:
      - cbz
      - cbr
      - zip
      - rar
      - 7z
      - pdf
    # 支持的图片格式
    supported-images:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - webp
    # 扫描线程数
    thread-count: 4
    # 批处理大小
    batch-size: 100
  
  # 阅读配置
  reading:
    # 默认阅读模式
    default-mode: single
    # 预加载页数
    preload-pages: 3
    # 自动保存阅读进度间隔（秒）
    auto-save-interval: 30
  
  # 安全配置
  security:
    # 允许的CORS源
    allowed-origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
      - "file://"
    # JWT密钥（如果需要认证）
    jwt-secret: "manhua-reader-secret-key-change-in-production"
    # JWT过期时间（小时）
    jwt-expiration: 24

# 日志配置
logging:
  level:
    com.manhua: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${app.data-path}/logs/manhua-reader.log
    max-size: 10MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# 应用信息
info:
  app:
    name: 漫画阅读器
    description: 一个现代化的漫画阅读应用程序
    version: 1.0.0
    author: Manhua Reader Team