# 应用配置
spring:
  application:
    name: manhua-reader-backend

  # 数据库配置 - H2混合模式
  datasource:
    url: jdbc:h2:file:./data/manhua;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC

  # Web配置
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  # 缓存配置
  cache:
    type: simple
    cache-names:
      - manga-covers
      - manga-pages
      - library-scan
      - file-info

  # 安全配置
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

  # 执行器配置
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,env
    endpoint:
      health:
        show-details: when-authorized

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# 日志配置
logging:
  level:
    com.manhua: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/manhua-reader.log
    max-size: 10MB
    max-history: 30

# 应用自定义配置
manhua:
  # 数据目录
  data-dir: ./data

  # 缓存目录
  cache-dir: ./cache

  # 临时目录
  temp-dir: ./temp

  # 日志目录
  log-dir: ./logs

  # 扫描配置
  scan:
    # 并发线程数
    thread-pool-size: 4
    # 扫描间隔（秒）
    interval: 300
    # 支持的图片格式
    supported-image-formats:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - webp
    # 支持的压缩格式
    supported-archive-formats:
      - zip
      - rar
      - 7z
      - cbz
      - cbr

  # 图片处理配置
  image:
    # 缩略图大小
    thumbnail-size: 300
    # 封面大小
    cover-size: 600
    # 图片质量（0.0-1.0）
    quality: 0.85
    # 是否启用WebP格式
    enable-webp: true

  # 缓存配置
  cache:
    # 最大缓存大小（MB）
    max-size: 1024
    # 缓存过期时间（小时）
    expire-hours: 24
    # 预加载页数
    preload-pages: 3

  # 网络文件系统配置
  network:
    # 连接超时（秒）
    connect-timeout: 30
    # 读取超时（秒）
    read-timeout: 60
    # 重试次数
    retry-count: 3

  # 安全配置
  security:
    # 是否启用认证
    enable-auth: false
    # JWT密钥
    jwt-secret: manhua-reader-secret-key-2024
    # JWT过期时间（小时）
    jwt-expiration: 24
    # 是否启用CORS
    enable-cors: true
    # 允许的源
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:5173"
      - "http://127.0.0.1:3000"
      - "http://127.0.0.1:5173"

  # 性能配置
  performance:
    # 是否启用异步处理
    enable-async: true
    # 异步线程池大小
    async-pool-size: 8
    # 是否启用压缩
    enable-compression: true
    # 是否启用缓存
    enable-cache: true
